Tunnelsats/tunnelsats

scripts/setupv2.sh
scripts/uninstallv2.sh

Fixes #1 and improves overall install|uninstall routines for all interfaces

ip leakage for lightningd in non-docker setup fixed

---

FAQ.md
frontend/client/package.json
frontend/client/src/App.js
frontend/client/src/components/RuntimeSelector.js
frontend/client/src/timefunction.js
frontend/client/webpack.config.js
frontend/server/server.js
scripts/setupv2.sh

- enhanced description for the user on how to proceed installation (editing config)
- include dotenv functionality for frontend usage to optimize code base for dynamic settings (links, prices, websocket)
- cleanup of the faq page that got messy on a previous merge

merge dev: setupv2 descriptions, env functionality, faq cleanup

---

frontend/client/src/App.js
scripts/setupv2.sh

Remove a lonesome dot. Persistent connection in wg conf.

blitzapi: typo, persistent connection in wg conf

---

frontend/client/src/App.js
frontend/client/src/timefunction.js
frontend/server/server.js

[dev to main]
Hotfix: getWireguardConfig, TS logo

Hotfix: getWireguardConfig, TS logo

---

frontend/server/package.json
frontend/server/server.js

Delete Invoice Data only when payment request expired not when 15 minutes passed since creation

Bolt11 decoder

---

frontend/client/src/components/WorldMap.js
frontend/client/src/components/WorldMapRenew.js
frontend/server/package.json
frontend/server/server.js
scripts/setupv2.sh

This PR merges various fixes and changes from dev branch to main. 
- new VPN (LatAM - located in Sao Paolo) is enabled
- pointer events are disabled for WorldMap on renewal page
- for umbrel setups: resolvconf is being installed to ensure successful curl test
- setupv2: apt is used instead of apt-get, fixes #40 
- bugfix: check for invoices on webhook
- removal of expired invoices from memory
- scirpts are adapted to latest RaspiBolt CLN guide (renaming cln -> lightningd), fixes #41 
- smaller changes

enable LatAM-VPN & more changes

---

scripts/check.sh

Fixes #22 
This PR provides an additional script for customers (especially running bare metal setups) to check for minimum requirements needed to install TunnelSats. It gathers system information and checks it against our criterias:
- linux kernel version
- nftables version (if installed) or support (from apt repo)
- systemd services and naming
- docker container and their port assignments
- ... things to come

compatibility check script

---

scripts/setupv2.sh

bugfix: nftables rule

---

scripts/setupv2.sh

fix: umbrel stop/start cmds, final message

---

frontend/client/package.json
frontend/client/src/App.js
frontend/client/src/index.css
frontend/server/server.js

contains: 
- last commit hash of github repo displayed in right corner of navbar (on click: links to the actual commit)
- reactivate de1 for renewals
- npm build: set `max-old-space=1024` within `package.json`, fixes error when building on limited memory
- uncommented unused css tags

Update: dev-1.0.2

---

frontend/client/src/components/WorldMap.js
frontend/server/server.js

In addition add data consistency check before allowing invoice to be created

bugfix when map is selected twice

---

FAQ.md

Also some minor adjustments to text blurps

Added more VPN providers

---

scripts/setupv2.sh

Local Network Access was not allowed when running the service in the tunnel, type local does not count for the local network addresses (as I though before)

Bugfix killswitch

---

scripts/resolve-dns-wg.sh
scripts/setupv2.sh
scripts/uninstallv2.sh

Add automatic resolve of the wg interface

Resolve dns wg

---

scripts/setupv2.sh

Also limit nondocker killswitch for raspiblitz users only, bc for other users we do not know the user lnd/cln runs as

change link to own repo for dns-resolve for wg.

---

FAQ.md
frontend/client/src/App.js
frontend/client/src/components/HeaderInfo.js
frontend/client/src/components/WorldMap.js
frontend/client/src/index.css
frontend/server/server.js
scripts/setupv2.sh

- reworked email text
- applied new location to EU VPN: DE2 - Frankfurt-> Nuremberg (preparing switch)
- removed duplicated chmod command
- add faq entry: how to switch de2 to de3

Update: dev 1.0.4

---

scripts/setupv2.sh

raspiblitz-killswitch-bugfix

---

.vscode/settings.json
FAQ.md

Minor improvements to the phasingout de2. 
Additionally, the .md linter/autoformatter might made some minor
adjustments to formatting.

Minor changes to FAQ.md

---

FAQ.md
frontend/client/package.json
frontend/client/src/App.js
frontend/client/src/components/HeaderInfo.js
frontend/client/src/components/WorldMap.js
frontend/client/src/index.css

This update contains the following frontend changes:
- expose uptime and ping times status page (upptime/upptime) as subdomain: https://status.tunnelsats.com
- showing planned VPN maintenances and status updates
- add server status link to navbar
- move important announcements to toast popups (removable by click, right upper side)
- FAQ: edit providers - remove Contabo, add Hetzner plus few rewordings
- WorldMap: make use of upptime to add ping and uptime stats per VPN to tooltips
Fixes #42

[UPDATE] dev 1.0.5

---

FAQ.md
README.md
frontend/client/src/App.js
frontend/client/src/components/HeaderInfo.js
frontend/server/package.json
scripts/archive/setup.sh
scripts/setupv2.sh

This PR prepares the existing repository located in 
https://github.com/blckbx/tunnelsats
for its planned migration to the organisational TunnelSats repo:
https://github.com/tunnelsats/
Todos:
- modify links and stuff in guide: README.md
- modify links and stuff in FAQ: FAQ.md
- check scripts for links (curl, wget)
- check website frontend for links (guide, faq, github,...)
- ...

[REPO]: migration

---

frontend/client/src/App.js
frontend/client/src/components/WindowSize.js

Fixes #91 
This PR fixes the navbar in mobile view by aggregating menu links into a dropdown menu when screen width < 1000 px.
Preview provided in dev environment.

website: fix navbar for mobile view

---

scripts/amboss-health-docker.sh
scripts/amboss-health-non-docker.sh
scripts/amboss-health-plain.sh
scripts/setup-amboss.sh

- setup amboss
- bugfix
- minor changes

Some Minor Changes

---

frontend/client/src/App.js
frontend/client/src/components/WorldMap.js

Improving WorldMap:
- show selected city w/ flag in world map area
- clarifying ping source (us based)
- show flags in tooltips

WorldMap: improve UX

---

frontend/client/src/App.js
frontend/client/src/components/WorldMap.js
frontend/server/server.js

Due to capacity limitations, we need to add a new VPN server for the European continent. 
This PR adds de2.tunnelsats.com to the frontend and makes it the default for Europe. 
The server is hosted by Hetzner and also located in Nuremberg.

[Frontend Update] new default VPN server for Europe (de2)

---

FAQ.md

Small PR updates supported versions in `FAQ.md` staying consistent with `README.md`.

faq: update supported versions

---

FAQ.md

- added our TunnelPingBot
- small link adjustment to the self-build guide

🤖 Bot adjustments (tiny)

---

FAQ.md

- added TOC Summary topics
- cleaned up sequence to group FAQ entries closer together

Parent Topics for TOC and sequence cleanup

---

frontend/client/src/components/WorldMap.js

This PR adjusts the uptime in each country's tooltip to match upptimes "server status" page.

[frontend] adjust uptime tooltip

---

frontend/client/package.json

frontend client: raise max-old-space-size

---

frontend/server/server.js

Fixing broken city to serverURL link and renaming env vars for consistency.

bugfix: broken city to serverURL association

---

scripts/setupv2.sh

Three things adjusted
- checking for users umbrel at the beginning, prompting the install with a custom text since Umbrel plans for a number of adjustments adding Hybrid settings [available in their UI](https://community.umbrel.com/t/lnd-tor-clearnet-how-to-setup-hybrid-mode/6133/78?u=hakuna)
- switched back from `apt install` to `apt-get install` since the former isn't supported for script execution, showing some annoying errors
- updated subdomain for the guide

umbrel UI adjustements + switch to apt-get

---

scripts/setupv2.sh

- Fix #126 
- small prompt simplification
- tiny `apt-get` adjustment
- footer expanded with useful post installation links

Setup script adjustments

---

scripts/setupv2.sh

script ended in:
Welcome to Tunnel⚡Sats.
- Feel free to join the Amboss Community: https://amboss.space/community/29db5f25-24bb-407e-b752-be69f9431071 ./setupv2.sh: line 1291: -: command not found
./setupv2.sh: line 1292: -: command not found
./setupv2.sh: line 1293: -: command not found

fix echo ending

---

scripts/setupv2.sh
scripts/uninstallv2.sh

This PR adds support for latest Umbrel modifications (v1.1) and tries to hotfix disappearing TS network bridge on system reboot.

[bugfix] support latest Umbrel modifications

---

FAQ.md
scripts/tunnelsats-sub-details.sh

mini script to provide local infos about
- WG Pubkey
- Transfer (since last restart)
- Latest Handshake
And point user to renew section / reminder bot
Tested on Umbrel and Raspiblitz

bash-script for TS details

---

scripts/check.sh

Fixing kernel version check taking major versions > 5 into account.

fix: kernel version check

---

frontend/client/src/App.js

We'll switch for website Telegram Group referrals to invite and approval only workflow

adjust to invite + approval only

---

frontend/server/server.js

cleaning up stale branches, please review your own and approve for a merge

Increase Data Cleanup from 10 min to 1 hour.
